### ISSUE TITLE
[Feature Suggestion] PWA (Progressive Web App)

### ISSUE THREAD

**Issue by deanilvincent** [tannerkrewson/drawphone#66] opened 2020-09-01 06:47 UTC
Hi,

Drawphone is an amazing application :) Hopefully, there will be PWA feature in the future like "Add to Homescreen."

**Comment by tannerkrewson** [comment] 2020-09-05 15:13
thanks for your suggestion; i completely agree. I've done this in spyfall, but i'm going to remove it, and not implement it for drawphone, in favor of adding the functionality to [rocketcrab](https://github.com/tannerkrewson/rocketcrab) 👍

**Comment by tannerkrewson** [comment] 2020-09-05 15:14
dupe of #35

**Closed as completed by tannerkrewson** 2020-09-05 15:13 UTC
